version: '2'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
  proxysql:
    image: severalnines/proxysql:2.0
    ports:
      - '6033:6033'
      - '6032:6032'
      - '6080:6080'
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
